package app.quietagent.workspace;

import android.content.ContentResolver;
import android.content.Context;
import android.database.Cursor;
import android.net.Uri;
import android.provider.DocumentsContract;
import java.io.*;
import java.nio.file.*;
import java.security.MessageDigest;
import java.util.*;

/** Small capability checked file boundary. Resource ids and paths never contain provider URIs. */
public final class WorkspaceFileAccess {
  public static final long MAX_FILE=20L*1024*1024, MAX_READ=200L*1024*1024;
  public static final class Stat { public final String id,name; public final boolean directory; public final long size,modified; public final String fingerprint;
    Stat(String i,String n,boolean d,long s,long m,String f){id=i;name=n;directory=d;size=s;modified=m;fingerprint=f;} }
  public static final class Resource { public final String id,name; public final boolean directory; public final long size; Resource(String i,String n,boolean d,long s){id=i;name=n;directory=d;size=s;} }
  public static final class Page { public final List<Resource> resources; public final String next; Page(List<Resource> r,String n){resources=r;next=n;} }
  public interface Permission { boolean canRead(); boolean canWrite(); }
  public interface Backend { Stat stat(String path)throws IOException; List<Stat> list(String path)throws IOException; InputStream open(String path)throws IOException; OutputStream create(String path,boolean truncate)throws IOException; void mkdir(String path)throws IOException; void rename(String path,String name)throws IOException; void copy(String from,String to)throws IOException; void move(String from,String to)throws IOException; void trash(String path)throws IOException; }
  public static final class LocalBackend implements Backend {
    private final Path root; public LocalBackend(Path r){root=r.toAbsolutePath().normalize();}
    private Path p(String s)throws IOException { if(s==null||s.contains("..")||s.startsWith("/")||s.startsWith("\\")||s.contains("\\"))throw new IOException("非法路径"); Path x=root.resolve(s).normalize();if(!x.startsWith(root))throw new IOException("越界路径");try{Path rr=Files.exists(x)?x.toRealPath():x.getParent().toRealPath().resolve(x.getFileName()).normalize();if(!rr.startsWith(root.toRealPath()))throw new IOException("符号链接越界");}catch(NoSuchFileException e){}return x; }
    public Stat stat(String s)throws IOException{Path x=p(s);if(!Files.exists(x))throw new FileNotFoundException(s);return new Stat(s,x.getFileName().toString(),Files.isDirectory(x),Files.isDirectory(x)?0:Files.size(x),Files.getLastModifiedTime(x).toMillis(),fingerprint(x));}
    public List<Stat> list(String s)throws IOException{Path x=p(s);List<Stat> o=new ArrayList<>();try(DirectoryStream<Path> ds=Files.newDirectoryStream(x)){for(Path q:ds)o.add(stat(root.relativize(q).toString().replace('\\','/')));}o.sort(Comparator.comparing(a->a.name));return o;}
    public InputStream open(String s)throws IOException{return Files.newInputStream(p(s));} public OutputStream create(String s,boolean t)throws IOException{Path x=p(s);Files.createDirectories(x.getParent());return Files.newOutputStream(x,t?new OpenOption[]{StandardOpenOption.CREATE,StandardOpenOption.TRUNCATE_EXISTING}:new OpenOption[]{StandardOpenOption.CREATE_NEW});}
    public void mkdir(String s)throws IOException{Files.createDirectories(p(s));} public void rename(String s,String n)throws IOException{if(n==null||n.isEmpty()||n.contains("..")||n.contains("/")||n.contains("\\"))throw new IOException("非法名称");Path x=p(s);Files.move(x,x.resolveSibling(n));}
    public void copy(String a,String b)throws IOException{Path d=p(b);Files.createDirectories(d.getParent());Files.copy(p(a),d,StandardCopyOption.REPLACE_EXISTING);} public void move(String a,String b)throws IOException{Path d=p(b);Files.createDirectories(d.getParent());Files.move(p(a),d,StandardCopyOption.REPLACE_EXISTING);} public void trash(String s)throws IOException{Files.deleteIfExists(p(s));}
    static String fingerprint(Path p)throws IOException{if(Files.isDirectory(p))return "dir:"+Files.getLastModifiedTime(p).toMillis();try(InputStream i=Files.newInputStream(p)){return sha(i,MAX_FILE);}}
  }
  /** SAF implementation: every operation rechecks the persisted grant and requested flags. */
  public static final class SafBackend implements Backend {
    private final Context c; private final Uri tree; private final boolean write,file; public SafBackend(Context x,Uri t,boolean w){this(x,t,w,false);} public SafBackend(Context x,Uri t,boolean w,boolean f){c=x.getApplicationContext();tree=t;write=w;file=f;}
    private void grant(boolean mutate)throws IOException{int f=0;for(android.content.UriPermission p:c.getContentResolver().getPersistedUriPermissions())if(p.getUri().equals(tree)){if(p.isReadPermission())f|=1;if(p.isWritePermission())f|=2;}if((f&1)==0)throw new IOException("SAF读权限已撤销");if(mutate&&((f&2)==0||!write))throw new IOException("SAF写权限已撤销");}
    private Uri u(String path)throws IOException{grant(false);if(file&&path.isEmpty())return tree;if(file)throw new IOException("单文件不支持子路径");if(path==null||path.contains("..")||path.startsWith("/")||path.contains("\\"))throw new IOException("非法路径");String cur=DocumentsContract.getTreeDocumentId(tree);Uri x=DocumentsContract.buildDocumentUriUsingTree(tree,cur);for(String a:path.split("/")){if(a.isEmpty())continue;Uri ch=DocumentsContract.buildChildDocumentsUriUsingTree(tree,cur);String found=null;try(Cursor q=c.getContentResolver().query(ch,new String[]{DocumentsContract.Document.COLUMN_DOCUMENT_ID,DocumentsContract.Document.COLUMN_DISPLAY_NAME},null,null,null)){if(q!=null)while(q.moveToNext())if(a.equals(q.getString(1))){found=q.getString(0);break;}}if(found==null)throw new FileNotFoundException(path);cur=found;x=DocumentsContract.buildDocumentUriUsingTree(tree,cur);}return x;}
    private void flags(Uri x,int need)throws IOException{try(Cursor q=c.getContentResolver().query(x,new String[]{DocumentsContract.Document.COLUMN_FLAGS},null,null,null)){if(q==null||!q.moveToFirst())throw new IOException("SAF项目不存在");int f=q.getInt(0);if((f&need)!=need)throw new IOException("SAF项目不支持此操作");}}
    private Stat s(Uri x,String id)throws IOException{grant(false);try(Cursor q=c.getContentResolver().query(x,new String[]{DocumentsContract.Document.COLUMN_DISPLAY_NAME,DocumentsContract.Document.COLUMN_MIME_TYPE,DocumentsContract.Document.COLUMN_SIZE,DocumentsContract.Document.COLUMN_LAST_MODIFIED},null,null,null)){if(q==null||!q.moveToFirst())throw new FileNotFoundException(id);String n=q.getString(0);boolean d=DocumentsContract.Document.MIME_TYPE_DIR.equals(q.getString(1));long z=q.isNull(2)?0:q.getLong(2),m=q.isNull(3)?0:q.getLong(3);return new Stat(id,n,d,z,m,"saf:"+m+":"+z);}}
    public Stat stat(String p)throws IOException{return s(u(p),p);} public List<Stat> list(String p)throws IOException{if(file)throw new IOException("单文件不支持目录列表");grant(false);Uri ch=DocumentsContract.buildChildDocumentsUriUsingTree(tree,DocumentsContract.getDocumentId(u(p)));List<Stat> o=new ArrayList<>();try(Cursor q=c.getContentResolver().query(ch,new String[]{DocumentsContract.Document.COLUMN_DOCUMENT_ID,DocumentsContract.Document.COLUMN_DISPLAY_NAME,DocumentsContract.Document.COLUMN_MIME_TYPE,DocumentsContract.Document.COLUMN_SIZE,DocumentsContract.Document.COLUMN_LAST_MODIFIED},null,null,null)){if(q!=null)while(q.moveToNext()){String n=q.getString(1);String id=p.isEmpty()?n:p+"/"+n;o.add(new Stat(id,n,DocumentsContract.Document.MIME_TYPE_DIR.equals(q.getString(2)),q.isNull(3)?0:q.getLong(3),q.isNull(4)?0:q.getLong(4),"saf:"+(q.isNull(4)?0:q.getLong(4))+":"+(q.isNull(3)?0:q.getLong(3))));}}o.sort(Comparator.comparing(a->a.name));return o;}
    public InputStream open(String p)throws IOException{grant(false);InputStream i=c.getContentResolver().openInputStream(u(p));if(i==null)throw new IOException("无法打开文件");return i;} public OutputStream create(String p,boolean t)throws IOException{grant(true);Uri x;try{x=u(p);}catch(FileNotFoundException missing){x=null;}if(x!=null){flags(x,DocumentsContract.Document.FLAG_SUPPORTS_WRITE);if(t)return c.getContentResolver().openOutputStream(x,"wt");}int k=p.lastIndexOf('/');String par=k<0?"":p.substring(0,k),n=p.substring(k+1);Uri made=DocumentsContract.createDocument(c.getContentResolver(),u(par),mime(n),n);if(made==null)throw new IOException("无法创建文件");return c.getContentResolver().openOutputStream(made,"w");}
    private static String mime(String name){String n=name.toLowerCase(Locale.ROOT);if(n.endsWith(".csv"))return "text/csv";if(n.endsWith(".html")||n.endsWith(".htm"))return "text/html";if(n.endsWith(".md"))return "text/markdown";if(n.endsWith(".zip"))return "application/zip";return "text/plain";}
    public void mkdir(String p)throws IOException{grant(true);int k=p.lastIndexOf('/');Uri x=DocumentsContract.createDocument(c.getContentResolver(),u(k<0?"":p.substring(0,k)),DocumentsContract.Document.MIME_TYPE_DIR,p.substring(k+1));if(x==null)throw new IOException("无法创建目录");} public void rename(String p,String n)throws IOException{grant(true);flags(u(p),DocumentsContract.Document.FLAG_SUPPORTS_RENAME);if(!DocumentsContract.renameDocument(c.getContentResolver(),u(p),n).toString().isEmpty())return;throw new IOException("无法重命名");}
    public void copy(String a,String b)throws IOException{try(InputStream i=open(a);OutputStream o=create(b,true)){byte[]x=new byte[32768];int n;while((n=i.read(x))>=0)o.write(x,0,n);}} public void move(String a,String b)throws IOException{copy(a,b);trash(a);} public void trash(String p)throws IOException{grant(true);flags(u(p),DocumentsContract.Document.FLAG_SUPPORTS_DELETE);if(!DocumentsContract.deleteDocument(c.getContentResolver(),u(p)))throw new IOException("无法删除");}
  }
  static String sha(InputStream i,long max)throws IOException{try{MessageDigest m=MessageDigest.getInstance("SHA-256");byte[]b=new byte[32768];long z=0;int n;while((n=i.read(b))!=-1){z+=n;if(z>max)throw new IOException("文件超过20 MiB");m.update(b,0,n);}StringBuilder s=new StringBuilder();for(byte x:m.digest())s.append(String.format(Locale.ROOT,"%02x",x&255));return s.toString();}catch(java.security.GeneralSecurityException e){throw new IOException(e);}}
}
