package app.quietagent.workspace;
import android.content.Context; import android.database.Cursor; import android.net.Uri; import android.provider.OpenableColumns; import app.quietagent.OfficeText;
import java.io.*; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import java.util.*; import org.json.*;
/** Durable, capability-scoped workspace jobs. Raw files are private verification inputs only. */
public final class WorkspaceJobs {
 private WorkspaceJobs(){} public static final String VERSION="workspace-job-v3",AUTH_VERSION="workspace-auth-v3"; private static final long TTL=600000L,MAX_FILE=20L*1024*1024L,MAX_TOTAL=200L*1024*1024L;
 public static final class Prepared{public final String jobId,preview,payload,payloadHash;Prepared(String a,String b,String c,String d){jobId=a;preview=b;payload=c;payloadHash=d;}}
 public static File root(Context c){File f=new File(c.getFilesDir(),"workspace/jobs");f.mkdirs();return f;} private static String valid(String id)throws IOException{if(id==null||!id.matches("job-[a-f0-9-]{36}"))throw new IOException("任务编号无效");return id;} public static File dir(Context c,String id)throws IOException{File f=new File(root(c),valid(id));if(!f.isDirectory())throw new IOException("任务不存在");return f;}
 public static Prepared prepare(Context c,List<Uri> us,String request)throws Exception{if(us==null||us.isEmpty()||us.size()>4)throw new IOException("请选择1至4份文件");String id="job-"+UUID.randomUUID();File d=new File(root(c),id);if(!d.mkdirs())throw new IOException("无法创建任务目录");JSONArray fs=new JSONArray(),sent=new JSONArray();long total=0;try{for(int n=0;n<us.size();n++){String name=name(c,us.get(n),n);File raw=new File(d,"f"+n),txt=new File(d,"text"+n);long z=copy(c,us.get(n),raw);total+=z;if(total>MAX_TOTAL)throw new IOException("任务总大小超过200 MiB");String t="",state="";try{t=OfficeText.redact(OfficeText.extract(raw,name));}catch(Exception e){state="无法解析";}t=clean(t,8000);write(txt,t);fs.put(new JSONObject().put("id","f"+n).put("name",name).put("sha256",hash(raw)).put("textSha256",hash(t)).put("state",state));sent.put(new JSONObject().put("id","f"+n).put("name",name).put("excerpt",t));}String payload=new JSONObject().put("request",clean(request,600)).put("files",sent).toString(),ph=hash(payload);JSONObject s=new JSONObject().put("version",VERSION).put("jobId",id).put("request",clean(request,600)).put("files",fs).put("payload",payload).put("preview",payload).put("payloadHash",ph).put("localConsentVersion","workspace-local-v1").put("localConsentAt",System.currentTimeMillis()).put("state","PREPARED").put("createdAt",System.currentTimeMillis());write(new File(d,"spec.json"),s.toString());return new Prepared(id,payload,payload,ph);}catch(Exception e){delete(d);throw e;}}
 private static long copy(Context c,Uri u,File o)throws Exception{try(InputStream i=c.getContentResolver().openInputStream(u)){if(i==null)throw new IOException("无法读取文件");try(OutputStream x=new FileOutputStream(o)){byte[]b=new byte[32768];int n;long z=0;while((n=i.read(b))!=-1){z+=n;if(z>MAX_FILE)throw new IOException("单个文件超过20 MiB");x.write(b,0,n);}return z;}}}
 private static String name(Context c,Uri u,int n){try(Cursor q=c.getContentResolver().query(u,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(q!=null&&q.moveToFirst())return safe(q.getString(0));}catch(Exception ignored){}return safe(u.getLastPathSegment()==null?"file-"+n:u.getLastPathSegment());}private static String safe(String s){if(s==null||s.trim().isEmpty())s="file";return s.replace('\\','_').replace('/','_').replace('\u0000','_');}
 public static JSONObject load(Context c,String id)throws IOException{try{File f=new File(dir(c,id),"spec.json");if(!f.isFile())throw new IOException("任务不存在");return new JSONObject(read(f));}catch(JSONException e){throw new IOException("任务记录损坏",e);}}
 public static synchronized void approve(Context c,String id,String expected)throws IOException{try{File d=dir(c,id);JSONObject s=load(c,id);String payload=s.getString("payload");if(!"PREPARED".equals(s.optString("state"))||!expected.equals(s.optString("payloadHash"))||!expected.equals(hash(payload)))throw new IOException("授权预览已改变或已使用");s.put("state","AUTHORIZED").put("authorizedAt",System.currentTimeMillis()).put("authorizationNonce",UUID.randomUUID().toString()).put("authorizationVersion",AUTH_VERSION);write(new File(d,"spec.json"),s.toString());}catch(JSONException e){throw new IOException("无法保存授权",e);}}
 public static synchronized JSONObject consumeAuthorization(Context c,String id)throws IOException{try{File d=dir(c,id);JSONObject s=load(c,id);String payload=s.getString("payload");if(!"AUTHORIZED".equals(s.optString("state"))||System.currentTimeMillis()-s.getLong("authorizedAt")>TTL||!s.getString("payloadHash").equals(hash(payload)))throw new IOException("授权无效、已过期或已消费");s.put("state","RUNNING").put("consumedAt",System.currentTimeMillis());write(new File(d,"spec.json"),s.toString());return s;}catch(JSONException e){throw new IOException("授权记录损坏",e);}}
 public static synchronized void commitOutputs(Context c,String id)throws IOException{try{File d=dir(c,id);JSONObject s=load(c,id);if(!"RUNNING".equals(s.optString("state")))throw new IOException("任务未处于运行状态");JSONObject o=new JSONObject();for(String f:new String[]{"results.csv","summary.html","audit.log","audit.jsonl"}){File x=new File(d,f);if(x.isFile())o.put(f,hash(x));}if(!o.has("results.csv")||!o.has("summary.html")||!o.has("audit.jsonl"))throw new IOException("缺少完整输出审计");o.put("committedAt",System.currentTimeMillis());write(new File(d,"outputs.json"),o.toString());s.put("outputs",o).put("state","COMPLETED").put("completedAt",System.currentTimeMillis());write(new File(d,"spec.json"),s.toString());for(int i=0;i<4;i++){delete(new File(d,"f"+i));delete(new File(d,"text"+i));}}catch(JSONException e){throw new IOException("无法提交输出",e);}}
 public static String readResults(Context c,String id,String f)throws IOException{if(!Arrays.asList("results.csv","summary.html","audit.jsonl","audit.log").contains(f))throw new IOException("结果文件不被允许");File d=dir(c,id);JSONObject s=load(c,id);if(!"COMPLETED".equals(s.optString("state"))||!s.has("outputs"))throw new IOException("结果尚未完成或缺少校验");File x=new File(d,f);if(!x.isFile())throw new IOException("结果不存在");try{if(!s.getJSONObject("outputs").has(f)||!hash(x).equals(s.getJSONObject("outputs").getString(f)))throw new IOException("结果校验失败");}catch(JSONException e){throw new IOException(e);}return read(x);}
 public static synchronized void update(Context c,String id,String state,String failure)throws IOException{try{JSONObject s=load(c,id).put("state",state).put("updatedAt",System.currentTimeMillis());if(failure!=null)s.put("failure",clean(failure,400));write(new File(dir(c,id),"spec.json"),s.toString());}catch(JSONException e){throw new IOException("任务记录损坏",e);}}
 public static synchronized void phase(Context c,String id,String value)throws IOException{try{JSONObject s=load(c,id).put("phase",value).put("updatedAt",System.currentTimeMillis());write(new File(dir(c,id),"spec.json"),s.toString());}catch(JSONException e){throw new IOException("任务记录损坏",e);}}
 public static synchronized void fail(Context c,String id,String state,String failure)throws IOException{File d=dir(c,id);try{update(c,id,state,failure);}finally{for(int i=0;i<4;i++){delete(new File(d,"f"+i));delete(new File(d,"text"+i));}delete(new File(d,"results.csv"));delete(new File(d,"summary.html"));}}
 public static synchronized void recoverInterrupted(Context c,String activeId)throws IOException{File[] a=root(c).listFiles();if(a==null)return;for(File d:a)if(d.isDirectory()&&!d.getName().equals(activeId))try{JSONObject s=load(c,d.getName());if("RUNNING".equals(s.optString("state"))){s.put("state","INTERRUPTED").put("failure","服务中断，需要重新授权");write(new File(d,"spec.json"),s.toString());for(int i=0;i<4;i++){delete(new File(d,"f"+i));delete(new File(d,"text"+i));}}}catch(Exception ignored){}}
 public static String read(File f)throws IOException{return new String(java.nio.file.Files.readAllBytes(f.toPath()),StandardCharsets.UTF_8);}public static void write(File f,String v)throws IOException{File p=new File(f.getParentFile(),f.getName()+".part");try(FileOutputStream o=new FileOutputStream(p)){o.write(v.getBytes(StandardCharsets.UTF_8));o.getFD().sync();}if(!p.renameTo(f))throw new IOException("无法保存任务记录");}public static String hash(File f)throws IOException{try(InputStream i=new FileInputStream(f)){MessageDigest m=MessageDigest.getInstance("SHA-256");byte[]b=new byte[32768];int n;while((n=i.read(b))!=-1)m.update(b,0,n);return hex(m.digest());}catch(Exception e){throw new IOException(e);}}public static String hash(String s)throws IOException{try{return hex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IOException(e);}}private static String hex(byte[]b){StringBuilder s=new StringBuilder();for(byte x:b)s.append(String.format(Locale.ROOT,"%02x",x&255));return s.toString();}static String clean(String s,int n){s=s==null?"":s.replace('\u0000',' ').trim();return s.length()>n?s.substring(0,n):s;}public static void delete(File f){if(f==null||!f.exists())return;File[]a=f.listFiles();if(a!=null)for(File x:a)delete(x);f.delete();}
}
