package app.quietagent.workspace;

import android.app.*; import android.graphics.*; import android.graphics.drawable.GradientDrawable; import android.os.*; import android.view.*; import android.widget.*; import java.util.*;

/** Manages private SMS copies without touching the system SMS provider. */
public final class WorkspaceSmsActivity extends Activity {
  private static final int PAGE=Color.rgb(242,242,247),CARD=Color.WHITE,INK=Color.rgb(28,28,30),MUTED=Color.rgb(99,99,102),GREEN=Color.rgb(24,103,67),RED=Color.rgb(191,54,48);
  private WorkspaceStore store; private LinearLayout items; private TextView count; private Button selectAll,removeSelected;
  private final LinkedHashSet<String> selected=new LinkedHashSet<>(); private final LinkedHashMap<String,CheckBox> checks=new LinkedHashMap<>();

  @Override public void onCreate(Bundle b){super.onCreate(b);requestWindowFeature(Window.FEATURE_NO_TITLE);getWindow().setStatusBarColor(PAGE);getWindow().setNavigationBarColor(PAGE);if(Build.VERSION.SDK_INT>=23)getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);store=new WorkspaceStore(this);build();}
  private void build(){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(PAGE);LinearLayout page=column();page.setPadding(dp(20),dp(18),dp(20),dp(36));scroll.addView(page);TextView back=text("‹  工作区资料",16,GREEN);back.setPadding(0,0,0,dp(8));back.setOnClickListener(v->finish());page.addView(back);TextView title=text("短信副本",32,INK);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);page.addView(title);count=text("",15,MUTED);page.addView(count,margins(0,2,0,12));LinearLayout bulk=row();selectAll=button("全选",GREEN);selectAll.setOnClickListener(v->toggleAll());bulk.addView(selectAll,new LinearLayout.LayoutParams(0,dp(44),1));removeSelected=button("移出所选",RED);removeSelected.setOnClickListener(v->confirmRemove());LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(0,dp(44),1);rp.setMargins(dp(8),0,0,0);bulk.addView(removeSelected,rp);page.addView(bulk,margins(0,0,0,14));items=column();page.addView(items);page.addView(text("移出只删除 Quiet Agent 保存的副本。手机短信应用中的原短信不会改变，副本可从回收区恢复。",13,MUTED),margins(4,12,4,0));setContentView(scroll);refresh();}
  @Override protected void onResume(){super.onResume();if(items!=null)refresh();}
  private void refresh(){items.removeAllViews();checks.clear();try{List<WorkspaceFileAccess.Resource> files=store.listSmsImports();files.sort((a,b)->Long.compare(modified(b),modified(a)));Set<String> valid=new HashSet<>();for(WorkspaceFileAccess.Resource r:files)valid.add(r.id);selected.retainAll(valid);if(files.isEmpty()){count.setText("工作区中没有短信副本");LinearLayout empty=card();empty.addView(text("从首页“导入短信副本”添加后，会显示在这里。",15,MUTED));items.addView(empty);}else for(WorkspaceFileAccess.Resource r:files)addSms(r);updateBulk();}catch(Exception e){items.addView(text("短信副本不可读："+msg(e),14,RED));updateBulk();}}
  private void addSms(WorkspaceFileAccess.Resource r)throws Exception{String body=store.readText(r.id);String[] lines=body.split("\\r?\\n",3);String sender=value(lines,0,"发送方：","未知发送方"),when=value(lines,1,"时间：",formatTime(modified(r))),preview=value(lines,2,"正文：","");LinearLayout card=card(),heading=row();CheckBox check=new CheckBox(this);check.setChecked(selected.contains(r.id));check.setContentDescription("选择 "+sender);check.setOnCheckedChangeListener((b,on)->{if(on)selected.add(r.id);else selected.remove(r.id);updateBulk();});checks.put(r.id,check);heading.addView(check,new LinearLayout.LayoutParams(dp(44),dp(44)));LinearLayout words=column();TextView name=text(shorten(sender,18),17,INK);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);words.addView(name);TextView detail=text(shorten(when+" · "+preview,46),13,MUTED);detail.setMaxLines(2);detail.setEllipsize(android.text.TextUtils.TruncateAt.END);words.addView(detail,margins(0,4,0,0));heading.addView(words,new LinearLayout.LayoutParams(0,-2,1));card.addView(heading);Button open=button("查看副本",GREEN);open.setOnClickListener(v->new AlertDialog.Builder(this).setTitle(sender).setMessage(body).setPositiveButton("完成",null).show());card.addView(open,new LinearLayout.LayoutParams(-1,dp(42)));items.addView(card,margins(0,0,0,10));}
  private String value(String[] lines,int i,String prefix,String fallback){if(i>=lines.length)return fallback;String v=lines[i].trim();if(v.startsWith(prefix))v=v.substring(prefix.length()).trim();return v.isEmpty()?fallback:v;}
  private void toggleAll(){boolean all=!checks.isEmpty()&&selected.size()==checks.size();selected.clear();if(!all)selected.addAll(checks.keySet());for(CheckBox box:checks.values())box.setChecked(!all);updateBulk();}
  private void updateBulk(){if(count!=null&&!checks.isEmpty())count.setText("共 "+checks.size()+" 条 · 已选择 "+selected.size()+" 条");if(selectAll!=null)selectAll.setText(!checks.isEmpty()&&selected.size()==checks.size()?"取消全选":"全选");if(removeSelected!=null)removeSelected.setEnabled(!selected.isEmpty());}
  private void confirmRemove(){if(selected.isEmpty()){toast("请先选择短信副本");return;}final ArrayList<String> ids=new ArrayList<>(selected);new AlertDialog.Builder(this).setTitle("移出所选 "+ids.size()+" 条短信？").setMessage("只删除 Quiet Agent 副本，原短信不会改变。副本会先进入回收区。").setPositiveButton("移出工作区",(d,w)->{int ok=0,failed=0;for(String id:ids)try{store.trash(id);ok++;}catch(Exception e){failed++;}selected.clear();refresh();toast(failed==0?"已移出 "+ok+" 条短信副本":"已移出 "+ok+" 条，失败 "+failed+" 条");}).setNegativeButton("取消",null).show();}
  private long modified(WorkspaceFileAccess.Resource r){try{return store.stat(r.id).modified;}catch(Exception e){return 0;}}private String formatTime(long v){return v<=0?"时间未知":new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.getDefault()).format(new Date(v));}private String shorten(String s,int n){if(s==null)return"";s=s.replace('\n',' ').replace('\r',' ').trim();return s.length()<=n?s:s.substring(0,n)+"…";}
  private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}private LinearLayout card(){LinearLayout l=column();l.setPadding(dp(16),dp(15),dp(16),dp(15));l.setBackground(round(CARD,18));l.setElevation(dp(1));return l;}private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}private Button button(String s,int c){Button b=new Button(this);b.setText(s);b.setTextColor(c);b.setAllCaps(false);b.setBackground(round(Color.rgb(246,246,248),12));return b;}private GradientDrawable round(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private LinearLayout.LayoutParams margins(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private String msg(Exception e){return e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
}
