package app.quietagent.workspace;

import android.app.*; import android.graphics.*; import android.graphics.drawable.GradientDrawable; import android.os.*; import android.view.*; import android.widget.*; import java.util.*;

/** Named result list with preview, multi-select and recoverable deletion. */
public final class WorkspaceResultsActivity extends Activity {
  private static final int PAGE=Color.rgb(242,242,247),CARD=Color.WHITE,INK=Color.rgb(28,28,30),MUTED=Color.rgb(99,99,102),GREEN=Color.rgb(24,103,67),RED=Color.rgb(191,54,48);
  private WorkspaceStore store; private LinearLayout items; private TextView count; private Button selectAll,deleteSelected;
  private final LinkedHashSet<String> selected=new LinkedHashSet<>(); private final LinkedHashMap<String,CheckBox> checks=new LinkedHashMap<>();

  @Override public void onCreate(Bundle state){super.onCreate(state);requestWindowFeature(Window.FEATURE_NO_TITLE);getWindow().setStatusBarColor(PAGE);getWindow().setNavigationBarColor(PAGE);if(Build.VERSION.SDK_INT>=23)getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);store=new WorkspaceStore(this);build();}
  private void build(){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(PAGE);LinearLayout page=column();page.setPadding(dp(20),dp(18),dp(20),dp(36));scroll.addView(page);TextView back=text("‹  工作区资料",16,GREEN);back.setPadding(0,0,0,dp(8));back.setOnClickListener(v->finish());page.addView(back);TextView title=text("成果",32,INK);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);page.addView(title);count=text("",15,MUTED);page.addView(count,margins(0,2,0,12));LinearLayout bulk=row();selectAll=button("全选",GREEN);selectAll.setOnClickListener(v->toggleAll());bulk.addView(selectAll,new LinearLayout.LayoutParams(0,dp(44),1));deleteSelected=button("删除所选",RED);deleteSelected.setOnClickListener(v->confirmBatchDelete());LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,dp(44),1);bp.setMargins(dp(8),0,0,0);bulk.addView(deleteSelected,bp);page.addView(bulk,margins(0,0,0,14));items=column();page.addView(items);page.addView(text("删除的成果会先进入回收区，可在首页的“回收区”批量恢复或永久清除。",13,MUTED),margins(4,12,4,0));setContentView(scroll);refresh();}
  @Override protected void onResume(){super.onResume();if(items!=null)refresh();}

  private List<WorkspaceFileAccess.Resource> resultFiles()throws Exception{WorkspaceFileAccess.Page page=store.list(WorkspaceStore.PRIVATE_ROOT,"",0,500,true);List<WorkspaceFileAccess.Resource> files=new ArrayList<>();for(WorkspaceFileAccess.Resource r:page.resources)if(!r.directory&&!relative(r.id).startsWith("imports/"))files.add(r);files.sort((a,b)->Long.compare(modified(b),modified(a)));return files;}
  private void refresh(){items.removeAllViews();checks.clear();try{List<WorkspaceFileAccess.Resource> files=resultFiles();Set<String> valid=new HashSet<>();for(WorkspaceFileAccess.Resource r:files)valid.add(r.id);selected.retainAll(valid);if(files.isEmpty()){count.setText("还没有生成成果");LinearLayout empty=card();empty.addView(text("完成任务后，报告、表格和归档会出现在这里。",15,MUTED));items.addView(empty);}else for(WorkspaceFileAccess.Resource r:files)addResult(r);updateBulk();}catch(Exception e){items.addView(text("成果列表不可读："+msg(e),14,RED));updateBulk();}}
  private void addResult(WorkspaceFileAccess.Resource r)throws Exception{WorkspaceFileAccess.Stat stat=store.stat(r.id);LinearLayout card=card(),heading=row();CheckBox check=new CheckBox(this);check.setChecked(selected.contains(r.id));check.setContentDescription("选择 "+r.name);check.setOnCheckedChangeListener((b,on)->{if(on)selected.add(r.id);else selected.remove(r.id);updateBulk();});checks.put(r.id,check);heading.addView(check,new LinearLayout.LayoutParams(dp(44),dp(44)));LinearLayout words=column();TextView name=text(r.name,17,INK);name.setTypeface(Typeface.DEFAULT,Typeface.BOLD);words.addView(name);String path=relative(r.id);words.addView(text(formatTime(stat.modified)+" · "+formatSize(r.size)+(path.equals(r.name)?"":" · "+path),13,MUTED),margins(0,4,0,0));heading.addView(words,new LinearLayout.LayoutParams(0,-2,1));card.addView(heading);LinearLayout actions=row();Button open=button("查看",GREEN);open.setOnClickListener(v->preview(r));actions.addView(open,new LinearLayout.LayoutParams(0,dp(44),1));Button remove=button("删除",RED);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(0,dp(44),1);rp.setMargins(dp(8),0,0,0);actions.addView(remove,rp);remove.setOnClickListener(v->confirmDelete(r));card.addView(actions,margins(0,8,0,0));items.addView(card,margins(0,0,0,10));}
  private void toggleAll(){boolean all=!checks.isEmpty()&&selected.size()==checks.size();selected.clear();if(!all)selected.addAll(checks.keySet());for(Map.Entry<String,CheckBox> e:checks.entrySet())e.getValue().setChecked(!all);updateBulk();}
  private void updateBulk(){if(count!=null&&!checks.isEmpty())count.setText("共 "+checks.size()+" 个文件 · 已选择 "+selected.size()+" 个");if(selectAll!=null)selectAll.setText(!checks.isEmpty()&&selected.size()==checks.size()?"取消全选":"全选");if(deleteSelected!=null)deleteSelected.setEnabled(!selected.isEmpty());}
  private void confirmBatchDelete(){if(selected.isEmpty()){toast("请先选择成果");return;}final ArrayList<String> ids=new ArrayList<>(selected);new AlertDialog.Builder(this).setTitle("删除所选 "+ids.size()+" 个成果？").setMessage("这些文件会移入回收区，可以恢复。").setPositiveButton("删除",(d,w)->{int ok=0,failed=0;for(String id:ids)try{store.trash(id);ok++;}catch(Exception e){failed++;}selected.clear();refresh();toast(failed==0?"已将 "+ok+" 个成果移入回收区":"已删除 "+ok+" 个，失败 "+failed+" 个");}).setNegativeButton("取消",null).show();}
  private void preview(WorkspaceFileAccess.Resource r){try{WorkspaceFileAccess.Stat stat=store.stat(r.id);if(stat.name.toLowerCase(Locale.ROOT).endsWith(".csv")){showCsv(stat.name,store.readText(r.id));return;}String body;try{body=store.readText(r.id);if(body.length()>12000)body=body.substring(0,12000)+"\n\n…预览已截断";}catch(Exception unsupported){body="文件大小："+formatSize(stat.size)+"\n\n此类型可由助手读取，当前页面不直接预览。";}new AlertDialog.Builder(this).setTitle(stat.name).setMessage(body).setPositiveButton("完成",null).show();}catch(Exception e){error("无法打开成果",e);}}
  private void showCsv(String name,String source)throws Exception{CsvTableParser.Result parsed=CsvTableParser.parse(source,200,24);if(parsed.rows.isEmpty()){new AlertDialog.Builder(this).setTitle(name).setMessage("表格为空").setPositiveButton("完成",null).show();return;}int columns=0;for(List<String> r:parsed.rows)columns=Math.max(columns,r.size());int[] widths=new int[columns];for(List<String> r:parsed.rows)for(int c=0;c<r.size();c++)widths[c]=Math.max(widths[c],Math.min(16,r.get(c).length()));TableLayout table=new TableLayout(this);for(int ri=0;ri<parsed.rows.size();ri++){TableRow line=new TableRow(this);List<String> values=parsed.rows.get(ri);for(int c=0;c<columns;c++){TextView cell=text(c<values.size()?values.get(c):"",ri==0?14:13,INK);if(ri==0)cell.setTypeface(Typeface.DEFAULT,Typeface.BOLD);cell.setPadding(dp(10),dp(9),dp(10),dp(9));cell.setBackground(tableCell(ri==0,ri%2==0));line.addView(cell,new TableRow.LayoutParams(dp(Math.max(100,Math.min(210,44+widths[c]*11))),-2));}table.addView(line);}HorizontalScrollView horizontal=new HorizontalScrollView(this);horizontal.addView(table);ScrollView vertical=new ScrollView(this);vertical.addView(horizontal);LinearLayout content=column();content.addView(text("共 "+parsed.rows.size()+" 行 · "+columns+" 列"+(parsed.truncated?" · 仅显示前 200 行":""),13,MUTED),margins(4,0,4,10));content.addView(vertical,new LinearLayout.LayoutParams(-1,dp(480)));new AlertDialog.Builder(this).setTitle(name).setView(content).setPositiveButton("完成",null).show();}
  private GradientDrawable tableCell(boolean header,boolean alternate){GradientDrawable g=round(header?Color.rgb(232,244,237):alternate?Color.rgb(248,248,250):Color.WHITE,0);g.setStroke(dp(1),Color.rgb(220,220,225));return g;}
  private void confirmDelete(WorkspaceFileAccess.Resource r){new AlertDialog.Builder(this).setTitle("删除“"+r.name+"”？").setMessage("文件会移入 Quiet Agent 回收区，不会立即永久清除。").setPositiveButton("删除",(d,w)->{try{store.trash(r.id);selected.remove(r.id);refresh();toast("已移入回收区");}catch(Exception e){error("删除失败",e);}}).setNegativeButton("取消",null).show();}
  private long modified(WorkspaceFileAccess.Resource r){try{return store.stat(r.id).modified;}catch(Exception ignored){return 0;}}private String formatTime(long v){return v<=0?"时间未知":new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.getDefault()).format(new Date(v));}private String relative(String id){int p=id.indexOf(':');return p>=0?id.substring(p+1):id;}private String formatSize(long n){if(n<1024)return n+" B";if(n<1024*1024)return String.format(Locale.ROOT,"%.1f KB",n/1024.0);return String.format(Locale.ROOT,"%.1f MB",n/(1024.0*1024.0));}
  private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;}private LinearLayout card(){LinearLayout l=column();l.setPadding(dp(16),dp(15),dp(16),dp(15));l.setBackground(round(CARD,18));l.setElevation(dp(1));return l;}private TextView text(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);return t;}private Button button(String s,int c){Button b=new Button(this);b.setText(s);b.setTextColor(c);b.setAllCaps(false);b.setBackground(round(Color.rgb(246,246,248),12));return b;}private GradientDrawable round(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(r));return g;}private LinearLayout.LayoutParams margins(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}private void error(String t,Exception e){new AlertDialog.Builder(this).setTitle(t).setMessage(msg(e)).setPositiveButton("好",null).show();}private String msg(Exception e){return e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
}
