package app.quietagent.workspace;

import android.content.Context; import android.net.Uri; import java.io.*; import java.nio.charset.StandardCharsets; import java.nio.file.*; import java.util.*; import org.json.*;

/** Unified, durable resource namespace for SAF roots and the private results root. */
public final class WorkspaceStore {
  public static final class RecycleItem {public final String id,name,path,rootName,sha256;public final long size,createdAt;RecycleItem(String i,String n,String p,String r,String h,long s,long c){id=i;name=n;path=p;rootName=r;sha256=h;size=s;createdAt=c;}}
  public static final String PRIVATE_ROOT="private"; private static final Object GLOBAL_LOCK=new Object(); private final Object lock=GLOBAL_LOCK; private final File state; private final File privateRoot; private final File control; private final Context context; private final LinkedHashMap<String,Root> roots=new LinkedHashMap<>();
  private static final class Root {String id,name,uri;boolean file,write;WorkspaceFileAccess.Backend backend;Root(String i,String n,String u,boolean f,boolean w,WorkspaceFileAccess.Backend b){id=i;name=n;uri=u;file=f;write=w;backend=b;}}
  public WorkspaceStore(Context c){context=c.getApplicationContext();privateRoot=new File(c.getFilesDir(),"workspace/results");control=new File(c.getFilesDir(),"workspace/control");privateRoot.mkdirs();control.mkdirs();state=new File(c.getFilesDir(),"workspace/roots.json");load();roots.put(PRIVATE_ROOT,new Root(PRIVATE_ROOT,"成果",privateRoot.getAbsolutePath(),false,true,new WorkspaceFileAccess.LocalBackend(privateRoot.toPath())));}
  public WorkspaceStore(File root)throws IOException{context=null;privateRoot=root.getCanonicalFile();control=new File(privateRoot.getParentFile(),"control");privateRoot.mkdirs();control.mkdirs();state=new File(privateRoot.getParentFile(),"roots.json");roots.put(PRIVATE_ROOT,new Root(PRIVATE_ROOT,"成果",privateRoot.getAbsolutePath(),false,true,new WorkspaceFileAccess.LocalBackend(privateRoot.toPath())));}
  private void load(){try{reloadChecked();}catch(Exception ignored){}}
  private void reloadChecked()throws IOException{Root keep=roots.get(PRIVATE_ROOT);roots.clear();if(keep!=null)roots.put(PRIVATE_ROOT,keep);if(!state.isFile())return;try{JSONArray a=new JSONArray(new String(Files.readAllBytes(state.toPath()),StandardCharsets.UTF_8));for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);if(PRIVATE_ROOT.equals(o.optString("id")))continue;String id=o.getString("id"),u=o.getString("uri");boolean file=o.optBoolean("file"),write=o.optBoolean("write");WorkspaceFileAccess.Backend b=context==null?new WorkspaceFileAccess.LocalBackend(Paths.get(u)):new WorkspaceFileAccess.SafBackend(context,Uri.parse(u),write,file);roots.put(id,new Root(id,o.optString("name",id),u,file,write,b));}}catch(Exception e){throw new IOException("工作区授权记录损坏",e);}}
  private void save()throws IOException{JSONArray a=new JSONArray();for(Root r:roots.values())if(!PRIVATE_ROOT.equals(r.id))try{a.put(new JSONObject().put("id",r.id).put("name",r.name).put("uri",r.uri).put("file",r.file).put("write",r.write));}catch(JSONException e){throw new IOException(e);}File p=new File(state.getParentFile(),state.getName()+".part");try(FileOutputStream o=new FileOutputStream(p)){o.write(a.toString().getBytes(StandardCharsets.UTF_8));o.getFD().sync();}if(!p.renameTo(state)){try{Files.move(p.toPath(),state.toPath(),StandardCopyOption.REPLACE_EXISTING);}catch(Exception e){throw new IOException("无法保存工作区授权",e);}}}
  private static String id(){return "root-"+UUID.randomUUID().toString();} private Root root(String id)throws IOException{reloadChecked();Root r=roots.get(id);if(r==null)throw new IOException("资源根不存在或已撤销");return r;}
  public String rootLabel(String id)throws IOException{synchronized(lock){reloadChecked();Root r=root(id);return r.name+(r.write?"":"（只读）");}}
  String rootName(String id)throws IOException{synchronized(lock){reloadChecked();return root(id).name;}}
  String rootUri(String id)throws IOException{synchronized(lock){reloadChecked();return root(id).uri;}}
  boolean rootIsFile(String id)throws IOException{synchronized(lock){reloadChecked();return root(id).file;}}
  void updateRootName(String id,String name)throws IOException{synchronized(lock){reloadChecked();Root r=root(id);if(PRIVATE_ROOT.equals(id)||name==null||name.trim().isEmpty())return;r.name=name.trim();save();}}
  public void remove(String id)throws IOException{removeRoot(id);}
  public List<String> listRoots()throws IOException{synchronized(lock){reloadChecked();return new ArrayList<>(roots.keySet());}}
  /** Package bridge for the constrained executor; callers never receive filesystem paths. */
  WorkspaceFileAccess.Backend backend(String rootId)throws IOException{synchronized(lock){return root(rootId).backend;}}
  public String addTree(String name,Uri uri,int flags)throws IOException{return addTree(name,uri.toString(),flags,false);}
  public String addTree(String name,String uri,int flags,boolean file)throws IOException{synchronized(lock){reloadChecked();if(name==null||name.trim().isEmpty()||uri==null)throw new IOException("授权参数无效");boolean w=(flags&2)!=0;for(Root existing:roots.values())if(!PRIVATE_ROOT.equals(existing.id)&&uri.equals(existing.uri)){existing.name=name.trim();existing.write=existing.write||w;existing.file=file;existing.backend=context==null?new WorkspaceFileAccess.LocalBackend(Paths.get(uri)):new WorkspaceFileAccess.SafBackend(context,Uri.parse(uri),existing.write,file);existing.backend.stat("");save();return existing.id;}String id=id();WorkspaceFileAccess.Backend b=context==null?new WorkspaceFileAccess.LocalBackend(Paths.get(uri)):new WorkspaceFileAccess.SafBackend(context,Uri.parse(uri),w,file);b.stat("");roots.put(id,new Root(id,name.trim(),uri,file,w,b));save();return id;}}
  public void compactDuplicateRoots()throws IOException{synchronized(lock){reloadChecked();Set<String> seen=new HashSet<>();boolean changed=false;Iterator<Map.Entry<String,Root>> it=roots.entrySet().iterator();while(it.hasNext()){Map.Entry<String,Root> entry=it.next();Root r=entry.getValue();if(PRIVATE_ROOT.equals(r.id))continue;if(!seen.add(r.uri)){it.remove();changed=true;}}if(changed)save();}}
  public String addFile(String name,Uri uri,int flags)throws IOException{return addTree(name,uri.toString(),flags,true);}
  /** Imports SMS or other ephemeral text into private storage, never grants the source URI. */
  public String importText(String name,String text)throws IOException{synchronized(lock){String n=safeName(name);String rel="imports/"+System.currentTimeMillis()+"-"+n;Root r=roots.get(PRIVATE_ROOT);writeLocked(r,rel,text==null?"":text,null);return PRIVATE_ROOT+":"+rel;}}
  public List<WorkspaceFileAccess.Resource> listSmsImports()throws IOException{synchronized(lock){ArrayList<WorkspaceFileAccess.Resource> out=new ArrayList<>();try{WorkspaceFileAccess.Page page=list(PRIVATE_ROOT,"imports",0,500,false);for(WorkspaceFileAccess.Resource r:page.resources){String n=r.name.toLowerCase(Locale.ROOT);if(!r.directory&&(n.startsWith("sms-")||n.contains("-sms-")))out.add(r);}}catch(FileNotFoundException ignored){}return out;}}
  public void removeRoot(String id)throws IOException{synchronized(lock){reloadChecked();if(PRIVATE_ROOT.equals(id))throw new IOException("成果根不可撤销");if(roots.remove(id)==null)throw new IOException("资源根不存在");save();}}
  public WorkspaceFileAccess.Page list(String rootId,String relative,int offset,int limit,boolean recursive)throws IOException{synchronized(lock){Root r=root(rootId);if(r.file){WorkspaceFileAccess.Stat one=r.backend.stat("");if(offset>0)return new WorkspaceFileAccess.Page(Collections.<WorkspaceFileAccess.Resource>emptyList(),null);return new WorkspaceFileAccess.Page(Collections.singletonList(new WorkspaceFileAccess.Resource(rootId+":",one.name,false,one.size)),null);}if(offset<0||limit<1||limit>500)throw new IOException("分页参数无效");List<WorkspaceFileAccess.Stat> all=new ArrayList<>();walk(r.backend,norm(relative),recursive,all);List<WorkspaceFileAccess.Resource> out=new ArrayList<>();for(int i=offset;i<Math.min(all.size(),offset+limit);i++){WorkspaceFileAccess.Stat s=all.get(i);out.add(new WorkspaceFileAccess.Resource(rootId+":"+s.id,s.name,s.directory,s.size));}return new WorkspaceFileAccess.Page(out,offset+limit<all.size()?Integer.toString(offset+limit):null);}}
  private void walk(WorkspaceFileAccess.Backend b,String p,boolean rec,List<WorkspaceFileAccess.Stat> out)throws IOException{for(WorkspaceFileAccess.Stat s:b.list(p)){out.add(s);if(rec&&s.directory)walk(b,s.id,true,out);}}
  public WorkspaceFileAccess.Stat stat(String scoped)throws IOException{String[] x=split(scoped);synchronized(lock){Root r=root(x[0]);return r.backend.stat(norm(x[1]));}}
  /** Resolves and capability-checks a scoped id on every call. */
  public WorkspaceFileAccess.Stat resolve(String scoped)throws IOException{return stat(scoped);}
  public byte[] readBytes(String scoped)throws IOException{synchronized(lock){WorkspaceFileAccess.Stat s=stat(scoped);if(s.directory||s.size>WorkspaceFileAccess.MAX_FILE)throw new IOException("文件超过20 MiB或不是文件");try(InputStream i=root(split(scoped)[0]).backend.open(norm(split(scoped)[1]))){ByteArrayOutputStream o=new ByteArrayOutputStream();byte[]b=new byte[32768];int n;long total=0;while((n=i.read(b))!=-1){total+=n;if(total>WorkspaceFileAccess.MAX_READ)throw new IOException("读取预算超限");o.write(b,0,n);}return o.toByteArray();}}}
  public byte[] snapshot(String scoped)throws IOException{return readBytes(scoped);}
  public String readText(String scoped)throws IOException{String[] x=split(scoped);String n=x[1].toLowerCase(Locale.ROOT);if(n.isEmpty())n=root(x[0]).backend.stat("").name.toLowerCase(Locale.ROOT);if(!(n.endsWith(".txt")||n.endsWith(".md")||n.endsWith(".csv")||n.endsWith(".html")))throw new IOException("仅允许编辑 txt/md/csv/html");return new String(readBytes(scoped),StandardCharsets.UTF_8);}
  public String find(String rootId,String query,boolean recursive)throws IOException{WorkspaceFileAccess.Page p=list(rootId,"",0,500,recursive);for(WorkspaceFileAccess.Resource r:p.resources)if(r.name.toLowerCase(Locale.ROOT).contains(query.toLowerCase(Locale.ROOT)))return r.id;return null;}
  public void mkdir(String parent,String name)throws IOException{mutate(parent,(b,p)->{b.mkdir(norm((p.isEmpty()?"":p+"/")+safeName(name)));return null;});}
  public void rename(String scoped,String name)throws IOException{if(split(scoped)[1].isEmpty()&&root(split(scoped)[0]).file)throw new IOException("单文件 provider 不支持安全重命名");mutate(scoped,(b,p)->{b.rename(p,safeName(name));return null;});}
  public void copy(String src,String dstDir)throws IOException{String[] a=split(src);String[] d=split(dstDir);synchronized(lock){Root ra=root(a[0]),rd=root(d[0]);if(!rd.write)throw new IOException("目标根没有写权限");String target=norm((d[1].isEmpty()?"":d[1]+"/")+ra.backend.stat(norm(a[1])).name);if(ra==rd&&norm(a[1]).equals(target))throw new IOException("源和目标相同");backupExisting(rd,target);try(InputStream i=ra.backend.open(norm(a[1]));OutputStream o=rd.backend.create(target,true)){byte[]b=new byte[32768];long total=0;int n;while((n=i.read(b))!=-1){total+=n;if(total>WorkspaceFileAccess.MAX_FILE)throw new IOException("文件超过20 MiB");o.write(b,0,n);}}if(!WorkspaceFileAccess.LocalBackend.class.isInstance(rd.backend)){} }}
  public void move(String src,String dstDir)throws IOException{String[] a=split(src),d=split(dstDir);synchronized(lock){Root ra=root(a[0]);Root rd=root(d[0]);if(!rd.write||!ra.write)throw new IOException("移动需要两侧写权限");String target=norm((d[1].isEmpty()?"":d[1]+"/")+new File(a[1]).getName());copy(src,dstDir);String h1=WorkspaceFileAccess.sha(ra.backend.open(norm(a[1])),WorkspaceFileAccess.MAX_FILE),h2=WorkspaceFileAccess.sha(rd.backend.open(target),WorkspaceFileAccess.MAX_FILE);if(!h1.equals(h2))throw new IOException("移动校验失败，源文件保留");ra.backend.trash(norm(a[1]));}}
  public void trash(String scoped)throws IOException{String[] x=split(scoped);synchronized(lock){Root r=root(x[0]);if(!r.write)throw new IOException("根没有写权限");journal("prepare-trash",x[0]);backupExisting(r,norm(x[1]));r.backend.trash(norm(x[1]));journal("complete-trash",x[0]);}}
  public String writeText(String scoped,String text,String expectedFingerprint)throws IOException{String[]x=split(scoped);String n=x[1].toLowerCase(Locale.ROOT);if(n.isEmpty())n=root(x[0]).backend.stat("").name.toLowerCase(Locale.ROOT);if(!(n.endsWith(".txt")||n.endsWith(".md")||n.endsWith(".csv")||n.endsWith(".html")))throw new IOException("仅允许编辑文本文件");synchronized(lock){Root r=root(x[0]);if(!r.write)throw new IOException("根没有写权限");WorkspaceFileAccess.Stat s=r.backend.stat(norm(x[1]));if(expectedFingerprint!=null&&!expectedFingerprint.equals(s.fingerprint))throw new IOException("外部修改，指纹不匹配");writeLocked(r,norm(x[1]),text,null);return r.backend.stat(norm(x[1])).fingerprint;}}
  public String create(String rootId,String relative,String text)throws IOException{String p=norm(relative);if(p.isEmpty()||!textName(p))throw new IOException("仅允许创建文本文件");synchronized(lock){Root r=root(rootId);if(!r.write)throw new IOException("根没有写权限");writeLocked(r,p,text,null);return rootId+":"+p;}}
  public String createBytes(String rootId,String relative,byte[] data)throws IOException{if(data==null||data.length>WorkspaceFileAccess.MAX_FILE)throw new IOException("结果过大");String p=norm(relative);if(!p.toLowerCase(Locale.ROOT).endsWith(".zip"))throw new IOException("二进制成果仅允许 ZIP");synchronized(lock){Root r=root(rootId);if(!r.write)throw new IOException("根没有写权限");journal("prepare-write",r.id);backupExisting(r,p);try(OutputStream o=r.backend.create(p,true)){o.write(data);}journal("complete-write",r.id);return rootId+":"+p;}}
  private void writeLocked(Root r,String p,String text,String expected)throws IOException{journal("prepare-write",r.id);backupExisting(r,p);byte[]b=(text==null?"":text).getBytes(StandardCharsets.UTF_8);if(b.length>WorkspaceFileAccess.MAX_FILE)throw new IOException("文件超过20 MiB");try(OutputStream o=r.backend.create(p,true)){o.write(b);}journal("complete-write",r.id);}
  private String backupExisting(Root r,String p)throws IOException{WorkspaceFileAccess.Stat before;try{before=r.backend.stat(p);}catch(FileNotFoundException e){return null;}String op=UUID.randomUUID().toString(),base=op+".bin";File bin=new File(control,base);try(InputStream i=r.backend.open(p);FileOutputStream o=new FileOutputStream(bin)){byte[]b=new byte[32768];int n;long z=0;while((n=i.read(b))!=-1){z+=n;if(z>WorkspaceFileAccess.MAX_FILE)throw new IOException("备份超过20 MiB");o.write(b,0,n);}o.flush();o.getFD().sync();}if(!before.fingerprint.equals(r.backend.stat(p).fingerprint)){bin.delete();throw new IOException("源文件在备份期间被外部修改");}String hash;try(InputStream i=new FileInputStream(bin)){hash=WorkspaceFileAccess.sha(i,WorkspaceFileAccess.MAX_FILE);}try{JSONObject m=new JSONObject().put("opId",op).put("sourceRootId",r.id).put("sourceRootName",r.name).put("sourcePath",p).put("sourceName",before.name).put("sourceSize",before.size).put("createdAt",System.currentTimeMillis()).put("fingerprint",before.fingerprint).put("sha256",hash).put("backup",base);try(FileOutputStream o=new FileOutputStream(new File(control,op+".json"))){o.write(m.toString().getBytes(StandardCharsets.UTF_8));o.getFD().sync();}}catch(JSONException e){throw new IOException(e);}return op;}
  private void journal(String phase,String root)throws IOException{File j=new File(control,"operation-journal.jsonl");try(FileOutputStream o=new FileOutputStream(j,true)){String s=System.currentTimeMillis()+"|"+phase+"|"+root+"\\n";o.write(s.getBytes(StandardCharsets.UTF_8));o.getFD().sync();}}
  public List<String> listRecycle(){String[] a=control.list((d,n)->n.endsWith(".json"));if(a==null)return Collections.emptyList();ArrayList<String> out=new ArrayList<>();for(String x:a)out.add(x.endsWith(".json")?x.substring(0,x.length()-5):x);return out;}
  public List<RecycleItem> listRecycleItems()throws IOException{synchronized(lock){ArrayList<RecycleItem> out=new ArrayList<>();for(String op:listRecycle()){File meta=new File(control,op+".json");try{JSONObject m=new JSONObject(new String(Files.readAllBytes(meta.toPath()),StandardCharsets.UTF_8));File bin=new File(control,m.optString("backup",op+".bin"));String path=m.optString("sourcePath","");String name=m.optString("sourceName",new File(path).getName());String rootName=m.optString("sourceRootName",m.optString("sourceRootId","工作区"));out.add(new RecycleItem(op,name,path,rootName,m.optString("sha256",""),m.optLong("sourceSize",bin.length()),m.optLong("createdAt",meta.lastModified())));}catch(Exception e){throw new IOException("回收项记录损坏",e);}}out.sort((a,b)->Long.compare(b.createdAt,a.createdAt));return out;}}
  public void restore(String opId)throws IOException{synchronized(lock){if(opId==null||!opId.matches("[a-f0-9-]{36}"))throw new IOException("回收项无效");try{JSONObject m=new JSONObject(new String(Files.readAllBytes(new File(control,opId+".json").toPath()),StandardCharsets.UTF_8));File b=new File(control,m.getString("backup"));try(InputStream i=new FileInputStream(b)){if(!WorkspaceFileAccess.sha(i,WorkspaceFileAccess.MAX_FILE).equals(m.getString("sha256")))throw new IOException("备份校验失败");}Root r=root(m.getString("sourceRootId"));String p=m.getString("sourcePath");try{r.backend.stat(p);int n=1;String q;do{q=p+".restored-"+n++;try{r.backend.stat(q);}catch(IOException e){p=q;break;}}while(n<1000);}catch(FileNotFoundException ignored){}try(InputStream i=new FileInputStream(b);OutputStream o=r.backend.create(p,false)){byte[]x=new byte[32768];int z;while((z=i.read(x))!=-1)o.write(x,0,z);}clearRecycle(opId);}catch(JSONException e){throw new IOException(e);}}}
  public void clearRecycle(String opId)throws IOException{synchronized(lock){if(opId==null||!opId.matches("[a-f0-9-]{36}"))throw new IOException("回收项无效");new File(control,opId+".json").delete();new File(control,opId+".bin").delete();}}
  private interface Op{Object run(WorkspaceFileAccess.Backend b,String p)throws IOException;} private void mutate(String scoped,Op op)throws IOException{synchronized(lock){String[]x=split(scoped);Root r=root(x[0]);if(!r.write)throw new IOException("根没有写权限");op.run(r.backend,norm(x[1]));}}
  private static boolean textName(String p){String n=p.toLowerCase(Locale.ROOT);return n.endsWith(".txt")||n.endsWith(".md")||n.endsWith(".csv")||n.endsWith(".html");}
  private static String[] split(String s)throws IOException{if(s==null){throw new IOException("资源ID为空");}int i=s.indexOf(':');if(i<=0)throw new IOException("资源ID无效");return new String[]{s.substring(0,i),norm(s.substring(i+1))};}
  private static String norm(String p)throws IOException{if(p==null||p.contains("..")||p.startsWith("/")||p.startsWith("\\")||p.contains("\\")||p.indexOf('\u0000')>=0)throw new IOException("非法路径");while(p.startsWith("/"))p=p.substring(1);return p;}
  private static String safeName(String n)throws IOException{if(n==null||n.trim().isEmpty()||n.contains("..")||n.contains("/")||n.contains("\\")||n.indexOf('\u0000')>=0)throw new IOException("非法名称");return n;}
}
